name: Kafka Integration Tests

on:
  push:
    branches: [ rabbit-and-running-app ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker build app
        run: |
          docker build ./src
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests
        working-directory: ./src
        run: docker-compose-app up --exit-code-from integration-tests integration-tests