name: Kafka Integration Tests

on:
  push:
    branches-ignore: [ without-app-running-in-pipeline ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker build app
        run: |
          docker build ./src
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests
        working-directory: ./src
        run: docker-compose -f ../docker-compose-app.yml up --exit-code-from integration-tests integration-tests